<?php
/*
*Nama Script: IndoWapBlog Multi Site
*Pembuat: Achunk JealousMan
*Email: achunk17[at]gmail[dot]com
*Situs: http://indowapblog.com
*Facebook: http://www.facebook.com/achunks
*/

eval(base64_decode("CgpkZWZpbmUoJ19JV0JfJywgMSk7CiRpZD1pc3NldCgkX0dFVFsnaWQnXSkgPyB0cmltKCRfR0VUWydpZCddKSA6ICcnOwpyZXF1aXJlKCdpbmMvaW5kb3dhcGJsb2cucGhwJyk7CmlmICghY3R5cGVfZGlnaXQoJGlkKSkKewokYno9Ijc3MjAyIjsKYWRzX2J1enpjaXR5KCRieik7CmFkc19idXp6Y2l0eSgkYnopOwphZHNfYnV6emNpdHkoJGJ6KTsKYWRzX2J1enpjaXR5KCRieik7Cn0KZWxzZQp7CiRjZWs9bXlzcWxfcXVlcnkoInNlbGVjdCAqIGZyb20gYHNwb25zb3JgIHdoZXJlIGBpZGA9JyIubXlzcWxfcmVhbF9lc2NhcGVfc3RyaW5nKCRpZCkuIicgYW5kIGBleHBpcmVkYCA+ICciLnRpbWUoKS4iJyIpOwppZiAobXlzcWxfbnVtX3Jvd3MoJGNlaykgPT0gMCkKewokYno9Ijc3MjAyIjsKYWRzX2J1enpjaXR5KCRieik7CmFkc19idXp6Y2l0eSgkYnopOwphZHNfYnV6emNpdHkoJGJ6KTsKYWRzX2J1enpjaXR5KCRieik7Cn0KZWxzZQp7CiRhZD1teXNxbF9mZXRjaF9hcnJheSgkY2VrKTsKJGtsaWsgPSAkYWRbJ2NsaWNrJ10gKyAxOwpteXNxbF9xdWVyeSgidXBkYXRlIHNwb25zb3Igc2V0IGNsaWNrPSciLiRrbGlrLiInIHdoZXJlIGlkPSciLiRhZFsnaWQnXS4iJyIpOwpoZWFkZXIoImxvY2F0aW9uOiAiLnN0cl9yZXBsYWNlKCcmYW1wOycsJyYnLGh0bWxzcGVjaWFsY2hhcnMoJGFkWyd1cmwnXSkpKTsKfQp9Cm15c3FsX2Nsb3NlKCRpd2JfY29ubmVjdCk7Cg=="));
?>